[project]
name = "models"
version = "0.1.0"
authors = [{ name = "Hinsun", email = "vanhoai.adv@gmail.com" }]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
models = "models:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
