[project]
name = "nn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Hinsun", email = "vanhoai.adv@gmail.com" }]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
nn = "nn:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
