[project]
name = "dl"
version = "0.1.0"
description = "🐳 Guideline to Deep Learning with PyTorch and Computer Vision"
readme = "README.md"
authors = [{ name = "Hinsun", email = "vanhoai.adv@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.7",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "tqdm>=4.67.1",
]
