[project]
name = "backend"
version = "0.1.0"
authors = [{ name = "Hinsun", email = "vanhoai.adv@gmail.com" }]
requires-python = ">=3.13"
dependencies = []

[tool.uv.sources]
core = { workspace = true }

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
